
name: Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 18.8.x

      - name: Install
        run: npm install

      - name: Playwright Install
        run: npx playwright install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test



